sudo: required

dist: trusty

language: node_js

node_js:
- '7'

before_install:
- npm install -g npm@5
- npm install -g greenkeeper-lockfile@1
- openssl aes-256-cbc -K $encrypted_1cd83addbd20_key -iv $encrypted_1cd83addbd20_iv
  -in deploy-key.enc -out deploy-key -d

install:
- npm install

before_script:
- greenkeeper-lockfile-update

script:
- npm run test

before_script:
- greenkeeper-lockfile-upload

after_success:
- bash bin/deploy.sh
