sudo: required
dist: trusty
language: node_js
node_js:
- '8'
- '9'
- '10'
before_install:
# Remove the line below once node 9 moves to LTS (and npm 5 is standard)
- npm install -g npm@5
install:
- npm install
script:
- cp local.config.js.tmpl local.config.js
- npm run build
- npm run test
after_success:
- npm install coveralls
- cat ./test/unit/coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js