---
# Installation steps
- hosts: all
  sudo: yes
  vars:
    apt_cache_valid_time: 86400
    nodejs_ppa: "ppa:chris-lea/node.js"
    libcrowds_user: "vagrant"
    libcrowds_path: "/vagrant"
  tasks:
    - name: check that Ubuntu is running
      assert:
        that:
          - ansible_distribution == 'Ubuntu'
          - ansible_distribution_release == 'trusty'

    - name: ensure ansible's apt_repository dependency is installed
      apt: pkg=python-apt state=latest update_cache=true cache_valid_time={{ apt_cache_valid_time }}

    - name: install git
      apt: name=git-core state=latest

    - name: ensure nodejs apt repository is up to date
      apt_repository: repo={{ nodejs_ppa }}

    - name: install Node.js
      apt: name=nodejs state=latest

    - name: install npm@latest
      apt: name=npm state=latest

    - name: check if local.config.js exists
      stat: path={{ libcrowds_path }}/local.config.js
      register: check_settings

    - name: copy default configuration template
      command: cp -p {{ libcrowds_path }}/local.config.js.tmpl {{ libcrowds_path }}/local.config.js
      when: not check_settings.stat.exists

    - name: install LibCrowds dependencies, this may take a while...
      sudo_user: "{{ libcrowds_user }}"
      command: npm install {{ libcrowds_path }}