---
# Installation steps
- hosts: all
  sudo: yes
  vars:
    apt_cache_valid_time: 86400
    libcrowds_user: "vagrant"
    libcrowds_path: "/vagrant"
  tasks:
    - name: check that Ubuntu is running
      assert:
        that:
          - ansible_distribution == 'Ubuntu'
          - ansible_distribution_release == 'trusty'

    - name: install git
      apt: name=git-core state=latest

    - name: install node 8 setup script
      command: curl -sL https://deb.nodesource.com/setup_8.x -o {{ libcrowds_path }}/nodesource_setup.sh

    - name: run node 8 setup script
      command: bash {{ libcrowds_path }}/nodesource_setup.sh

    - name: install Node.js
      apt: name=nodejs state=latest

    - name: install build-essential
      apt: name=build-essential state=latest

    - name: check if local.config.js exists
      stat: path={{ libcrowds_path }}/local.config.js
      register: check_settings

    - name: copy default configuration template
      command: cp -p {{ libcrowds_path }}/local.config.js.tmpl {{ libcrowds_path }}/local.config.js
      when: not check_settings.stat.exists

    - name: install LibCrowds dependencies, this may take a while...
      sudo_user: "{{ libcrowds_user }}"
      command: npm install {{ libcrowds_path }}

    - name: install bindings for node-sass
      command: npm rebuild node-sass {{ libcrowds_path }}